### ISSUE TITLE
NowPlaying Issues: Crashes Rainmeter & Buttons Do Not Work

### ISSUE THREAD

**Issue by eclectic-tech** [reisir/mondtholomew#2]
If you select 'PlayerPlugin=NowPlaying' and 'TitleExtraction=1' this will lockup and crash Rainmeter.
Setting 'TitleExtraction=0' eliminates the crash, but...

If you set 'PlayerName=Winamp' (or any NP supported player) the 'Next', 'PlayPause', and 'Previous' buttons do not work.
This can be corrected by modifying the 'Buttons.inc' file and changing **[MeasureStateButton]** section:

```
[MeasureStateButton]
Measure=Plugin
Plugin=#PlayerPlugin#
PlayerName=#PlayerName#
PlayerType=STATE
Substitute="0":"Play.png","1":"Pause.png","2":"Play.png"

```

Thanks for your work! Everything else works great!

Regards,
John aka Eclectic-Tech

**Comment by reisir** [comment]
Thanks for reporting, this same issue used to happen with WebNowPlaying too but once it magically stopped happening with WNP I evidently didn't bother to check with NowPlaying. 

I've now "fixed" this by just not allowing TitleExtraction to be used with NowPlaying. It was originally meant to remove redundant information present in YouTube videos (ie. artist name in both video title and channel name). Which hopefully isn't an issue in properly tagged local music collections to begin with.

Also the MeasureStateButton being in that file is a goof on my part, I left it there when testing. I really need to do some spring cleaning in the codebase...

**Comment by eclectic-tech** [comment]
Thanks for the "fix". Good to see this popular suite working again. Great job!
