### ISSUE TITLE
visualizer is broken?

### ISSUE THREAD

**Issue by thenameofallnames-ig** [reisir/mondtholomew#3]
it doesn't show up and if i check the registry, it throws m this error.
`Invalid FFTSize 3675: must be an even integer >= 0. (powers of 2 work best) (Mondtholomew\Visualizer\Visualizer.ini - [MeasureAudio])`

there's any way to fix this?

**Comment by reisir** [comment]
Check your audio devices sampling rate in Windows sound settings. Mondtholomew uses it to determine the optimal FFTSize and FFTOverlap. 

![image](https://user-images.githubusercontent.com/93496808/232759325-c0c76027-f551-4e8d-904a-ff8f7c1d647a.png)

The default for most devices is 48000. Use that if available. If it's not available, you can override the `MeasureSamplingRate` manually by adding `,".*":"48000"` to the end of the Substitute option.

So if you can't use 48000 as your devices sampling rate, go to `Mondtholomew\Visualizer\AudioLevel.inc` (Mondtholomew is in your Rainmeter skins folder, which is in Documents by default) and change line 14 to `Substitute="(Hz.*)$":"",".*":"48000"`

**Comment by thenameofallnames-ig** [comment]
whoa, the substitute edit thing did work. thank you!
