### ISSUE TITLE
Visualizer 

### ISSUE THREAD

**Issue by Bharathkumar1522** [reisir/mondtholomew#6]
Visualizer is not working

**Comment by reisir** [comment]
Make sure you have audio playing. Rainmeter also can't get audio from bluetooth audio devices. If neither of those resolve your issue, please explain what is wrong. "Visualizer is not working" is not sufficient information for me to diagnose the issue. Have you tried to fix it? Is there any errors in the Rainmeter log?

**Comment by Bharathkumar1522** [comment]
![Screenshot (346)](https://github.com/reisir/mondtholomew/assets/123487920/55d6921a-d5a6-4756-9196-1d09fce7bd18)

visualizer is not even showing on screen ! even while song is playing! No bluetooth audio devices connected! i'm using spotify mod

**Comment by reisir** [comment]
Do you have the visualizer loaded? It should show up if there's audio playing, doesn't matter where the audio is coming from. I don't know what spotify mod is and it doesn't really matter.. 

Anyway, to find the visualizer, change the `VisMinHeight` variable to be greater than 0. Then refresh Mondtholomew. If you don't know how to change the settings of Mondtholomew, read the [wiki](https://github.com/reisir/mondtholomew/wiki/Changing-settings).

Changing the minimum height will make the visualizer visible even if there's no audio playing. It could be on another screen or something, I don't really know why it wouldn't react to audio. 

If you find it and it really isn't reacting to audio, open the Rainmeter log (right click Rainmeter tray icon, choose About) and see if there's any errors or anything related to the visualizer.

**Comment by reisir** [comment]
Also, to get help faster, join the Rainmeter discord [https://discord.gg/rainmeter](https://discord.gg/rainmeter). I would prefer if GitHub issues were used for actual bug reports, not help requests.

**Comment by Bharathkumar1522** [comment]
yep I followed everything as you said ! now I have this scenario
![Screenshot (347)](https://github.com/reisir/mondtholomew/assets/123487920/de16b4c5-5d29-4f24-96d4-a7a2ddddfdcc)
can you see visualizer at bottom! it;s not responding

**Comment by reisir** [comment]
Check this: https://forum.rainmeter.net/viewtopic.php?t=27724
and if disabling the audio driver doesn't work: https://forum.rainmeter.net/viewtopic.php?f=119&t=23348

**Comment by reisir** [comment]
Closing as stale help request. If you need further assistance, join the [Rainmeter discord](https://discord.gg/rainmeter)
